# Production build (main branch)
[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://thesimpleai.vercel.app/api"

# Deploy contexts - separate production and test
[context.production]
  publish = "out"
  command = "npm run build"
  [context.production.environment]
    NEXT_TELEMETRY_DISABLED = "1"
    NODE_ENV = "production"
    NEXT_PUBLIC_API_URL = "https://thesimpleai.vercel.app/api"

# Test branch context - preview only
[context.test]
  publish = "out"
  command = "npm run build"
  [context.test.environment]
    NEXT_TELEMETRY_DISABLED = "1"
    NODE_ENV = "development"
    NEXT_PUBLIC_API_URL = "https://thesimpleai.vercel.app/api"

# Branch deploy context - for any other branches
[context.branch-deploy]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://thesimpleai.vercel.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://alcdn.msauth.net https://login.microsoftonline.com; connect-src 'self' https://login.microsoftonline.com https://graph.microsoft.com https://*.vercel.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; frame-src https://login.microsoftonline.com;"
    Cross-Origin-Opener-Policy = "unsafe-none"
    Cross-Origin-Embedder-Policy = "unsafe-none"
