[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://thesimpleai.vercel.app/api"

[[redirects]]
  from = "/api/*"
  to = "https://thesimpleai.vercel.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
