[build]
  command = "npm install"
  functions = "."
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/index/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
