# Railway deployment configuration
# This file tells Railway how to deploy your backend

version: 2

build:
  commands:
    - npm install
    - npm run init-db
    - npm run seed-db

start:
  command: npm start

env:
  NODE_ENV: production
  
# Health check
healthcheck:
  path: /health
  interval: 30s
  timeout: 10s